#QQEmail Config
#官方配置说明:http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=369
#获取客户端授权码:http://service.mail.qq.com/cgi-bin/help?subtype=1&&no=1001256&&id=28
spring:
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 1151757358@qq.com #QQ邮箱
    password: tpmlrrtlkqfggabe #客户端授权码
    protocol: smtp #发送邮件协议
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465 #端口号465或587
    properties.mail.display.sendmail: Javen #可以任意
    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: 1151757358@qq.com #与上面的username保持一致
#说明：开启SSL时使用587端口时无法连接QQ邮件服务器

#网易Email Config
#官方配置说明:http://mail.163.com/html/110127_imap/index.htm#tab=android
#获取客户端授权码:http://help.mail.163.com/faq.do?m=list&categoryID=197
#spring:
#  mail:
#    host: smtp.126.com
#    username: xx@126.com
#    password: xxxxxxxx
#    protocol: smtp
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.port: 994 #465或者994
#    properties.mail.display.sendmail: Javen
#    properties.mail.display.sendname: Spring Boot Guide Email
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
#    from: xx@126.com
#126邮箱SMTP服务器地址:smtp.126.com,端口号:465或者994
#163邮箱SMTP服务器地址:smtp.163.com,端口号:465或者994
#yeah邮箱SMTP服务器地址:smtp.yeah.net,端口号:465或者994

#GooleEmail Config
#官方配置说明:https://support.google.com/mail/answer/78754 需要科学上网
#spring:
#  mail:
#    host: smtp.gmail.com
#    username:xxx@gmail.com
#    password: xxxxx #Gmail账号密码
#    protocol: smtp
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.port: 465
#    properties.mail.display.sendmail: Javen
#    properties.mail.display.sendname: Spring Boot Guide Email
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    from: xxx@gmail.com
#    default-encoding: utf-8
#Gmail 发送邮件服务器为:smtp.gmail.com,端口号:465。客户端授权码为Gmail账号的密码，必须使用使用SSL。
#还需要开启允许不够安全的应用 ，不然会出现Authentication failed的异常
#选择登录与安全滑到底部有个允许不够安全的应用开启即可